"""RL-facing episodic environment wrapper.

This wrapper orchestrates latent generation, simulation, observation building,
reward computation, and termination checking while recording episode data.

Example usage:
    # env = Environment(n_max=5, reward_mode="step")
    # obs = env.reset()
    # for _ in range(5):
    #     obs, reward, done, info = env.step([0.0, 0.1])
    #     if done:
    #         break
"""

from __future__ import annotations

from typing import Any

from src.env.termination import TerminationChecker
from src.latent.generator import LatentGenerator
from src.obs.builder import ObservationBuilder
from src.reward.reward_fn import RewardFunction
from src.sim.simulator import Simulator
from src.utils.types import (
    ArrayLike,
    EpisodeRecord,
    HistoryLike,
    InfoDict,
    MetadataDict,
    RewardMode,
    StepRecord,
)


class Environment:
    """Minimal closed-loop environment with `reset()` and `step(action)`.

    `reset()`:
    - starts a new episode
    - samples/reset latent state
    - clears history buffers
    - returns an initial observation built from empty history

    `step(action)`:
    - advances one step
    - runs simulator + observation + termination + reward logic
    - records one StepRecord and updates current EpisodeRecord
    - returns `(observation, reward, done, info)`
    """

    def __init__(
        self,
        n_max: int,
        *,
        latent_generator: LatentGenerator | None = None,
        simulator: Simulator | None = None,
        observation_builder: ObservationBuilder | None = None,
        reward_function: RewardFunction | None = None,
        termination_checker: TerminationChecker | None = None,
        reward_mode: RewardMode | None = None,
        mc_config: MetadataDict | None = None,
        episode_id_start: int = 0,
    ) -> None:
        self.n_max = n_max
        self.latent_generator = latent_generator or LatentGenerator()
        self.simulator = simulator or Simulator()
        self.observation_builder = observation_builder or ObservationBuilder()
        self.reward_function = reward_function or RewardFunction()
        self.termination_checker = termination_checker or TerminationChecker(n_max=n_max)
        self.reward_mode: RewardMode = reward_mode or self.reward_function.reward_mode
        self.mc_config: MetadataDict = mc_config or {
            "enabled": False,
            "num_samples": 1,
            "aggregation": "none",
        }

        self._episode_id = episode_id_start
        self._step_index = 0
        self._latent: Any = None
        self._history: HistoryLike = self._new_history()
        self.current_episode: EpisodeRecord | None = None

    def reset(self) -> Any:
        """Reset environment state and return initial observation.

        Initial observation is built from empty history (`step_index=0`) and a
        reset aux marker. It is not stored as a StepRecord.
        """

        self._episode_id += 1
        self._step_index = 0
        self._history = self._new_history()
        self._latent = self.latent_generator.reset()

        self.current_episode = EpisodeRecord(
            episode_id=self._episode_id,
            n_max=self.n_max,
            latent_metadata={"latent_reset": self._latent},
            mc_metadata=dict(self.mc_config),
        )

        reset_aux: InfoDict = {"phase": "reset"}
        initial_observation = self.observation_builder.build(
            step_index=0,
            history=self._history,
            latest_readout=None,
            aux=reset_aux,
        )
        return initial_observation

    def step(self, action: ArrayLike) -> tuple[Any, float, bool, InfoDict]:
        """Advance one environment step.

        Args:
            action: Continuous, potentially high-dimensional control `theta_i`.

        Returns:
            observation: observation generated by ObservationBuilder.
            reward: step reward in step/combined mode, otherwise 0.0.
            done: episode termination flag.
            info: diagnostics including termination and episode summary when done.
        """

        if self.current_episode is None:
            raise RuntimeError("Environment.reset() must be called before step().")

        self._step_index += 1
        self._latent = self.latent_generator.step(self._step_index, self._latent)

        readout, aux = self.simulator.simulate_step(
            step_index=self._step_index,
            action=action,
            latent=self._latent,
            history=self._history,
            rng=None,
        )

        readout, aux = self._aggregate_mc_outputs(readout, aux)

        self._history["actions"].append(action)
        self._history["readouts"].append(readout)
        self._history["aux"].append(aux)

        observation = self.observation_builder.build(
            step_index=self._step_index,
            history=self._history,
            latest_readout=readout,
            aux=aux,
        )
        self._history["observations"].append(observation)

        done, reason = self.termination_checker.check(
            step_index=self._step_index,
            history=self._history,
            latest_readout=readout,
            aux=aux,
        )

        step_reward: float | None = None
        if self.reward_mode in ("step", "combined"):
            step_reward = self.reward_function.compute_step(
                step_index=self._step_index,
                history=self._history,
                latest_readout=readout,
                aux=aux,
            )
        self._history["rewards"].append(step_reward)

        info: InfoDict = {
            "step_index": self._step_index,
            "aux": aux,
            "mc": dict(self.mc_config),
        }
        if done:
            info["termination_reason"] = reason

        self.current_episode.add_step(
            StepRecord(
                step_index=self._step_index,
                action=action,
                readout=readout,
                observation=observation,
                reward=step_reward,
                done=done,
                info=dict(info),
            )
        )

        returned_reward = float(step_reward) if step_reward is not None else 0.0
        if done:
            self.current_episode.termination_reason = reason
            terminal_reward: float | None = None
            if self.reward_mode in ("terminal", "combined"):
                terminal_reward = self.reward_function.compute_terminal(self.current_episode)
                self.current_episode.terminal_reward = terminal_reward
                info["terminal_reward"] = terminal_reward

            info["episode_summary"] = {
                "episode_id": self.current_episode.episode_id,
                "length": self.current_episode.length,
                "n_max": self.current_episode.n_max,
                "termination_reason": self.current_episode.termination_reason,
                "terminal_reward": self.current_episode.terminal_reward,
            }

            if self.reward_mode == "terminal":
                returned_reward = 0.0

        return observation, returned_reward, done, info

    def _new_history(self) -> HistoryLike:
        """Create empty rollout history buffers."""

        return {
            "actions": [],
            "readouts": [],
            "observations": [],
            "rewards": [],
            "aux": [],
        }

    def _aggregate_mc_outputs(
        self,
        readout: ArrayLike,
        aux: InfoDict,
    ) -> tuple[ArrayLike, InfoDict]:
        """Monte Carlo aggregation hook (unused in single-sample stub mode)."""

        return readout, aux
